import Modal from '@/components/Modal'
import './globals.css'
import type { Metadata } from 'next'
import EditModal from '@/components/EditModal'



export const metadata: Metadata = {
  title: 'TaskFlow',
  description: 'Generated by Milind Nair',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        {children}
        <Modal />
        <EditModal />
      </body>
    </html>
  )
}
